# Generated by Django 5.0.6 on 2024-06-04 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_monitoring', '0002_symptom_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('date_prescribed', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_monitoring.doctor')),
                ('doctor_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_monitoring.doctorvisit')),
                ('medications', models.ManyToManyField(related_name='prescribed_treatments', to='health_monitoring.medication')),
                ('patient', models.ForeignKey(limit_choices_to={'role__key': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
