# Generated by Django 5.0.6 on 2024-06-05 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_monitoring', '0004_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvisit',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
